# Generated by Django 2.2 on 2020-10-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentity',
            name='mobile_phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=12, unique=True),
        ),
    ]
