# Generated by Django 2.2 on 2020-10-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20201008_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentity',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AddField(
            model_name='userentity',
            name='year_of_entry',
            field=models.IntegerField(null=True),
        ),
    ]
