# Generated by Django 2.2 on 2020-10-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auto_20201013_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentity',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userentity',
            name='is_staff',
        ),
    ]
