# Generated by Django 3.1.2 on 2020-11-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_auto_20201103_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentity',
            name='account_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userentity',
            name='full_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='userentity',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userentity',
            name='national_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userentity',
            name='study',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userentity',
            name='mobile_phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=12, null=True, unique=True),
        ),
    ]
