# Generated by Django 2.2 on 2020-12-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_auto_20201127_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentity',
            old_name='study',
            new_name='field_of_study',
        ),
    ]
