# Generated by Django 2.2 on 2020-12-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_auto_20201208_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentity',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'simple')], default=2),
        ),
    ]
