# Generated by Django 2.2 on 2021-01-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_auto_20201217_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userentity',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='userentity',
            name='otp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کد یکبار مصرف'),
        ),
    ]
