# Generated by Django 2.2 on 2021-02-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_auto_20210206_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentity',
            old_name='creadit',
            new_name='credit',
        ),
    ]
