# Generated by Django 2.2 on 2021-02-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0019_auto_20210206_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentity',
            name='checkout_requested',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
