class PayloadParamName:
    id = "id"
    result = "result"
    name = "name"
    description = "description"
    is_registered = "is_registered"
    camp_id = "camp_id"
    gender = "gender"
    year_of_entry = "year_of_entry"
    capacity = "capacity"
    cost = "cost"
    execution_time = "execution_time"
    user_id = "user_id"
    count = "count"