# Generated by Django 2.2 on 2021-02-06 07:57

import commons.models.base_entity
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='عنوان اردو')),
                ('description', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='جنسیت')),
                ('year_of_entry', models.CharField(max_length=50, verbose_name='سال ورودی  اردو')),
                ('capacity', models.IntegerField(default=20, verbose_name='ظرفیت')),
                ('image', models.ImageField(default='Images/None/No_img.jpg', upload_to='Images/', verbose_name='بارگذاری پوستر اردو')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='هزینه')),
                ('is_verified', models.BooleanField(verbose_name='تایید شده است')),
                ('verification_time', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید اردو')),
                ('is_canceled', models.BooleanField(default=0, verbose_name='کنسل شده است')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ کنسلی اردو')),
                ('execution_time', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ برگزاری اردو')),
                ('Registration_time_1', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع ثبت نام')),
                ('Registration_time_2', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان ثبت نام')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('deletion_time', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'اردوها',
                'db_table': 'campaign_entity',
            },
            bases=(commons.models.base_entity.BaseEntity, models.Model),
        ),
        migrations.CreateModel(
            name='RegisteredUsersEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_canceled', models.BooleanField(default=0, verbose_name='کنسل شده است')),
                ('canceled_by', models.IntegerField(choices=[(1, 'admin'), (2, 'simple')], default=None, verbose_name='کنسل شده توسط')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ کنسلی')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('deletion_time', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_users', to='reserve.CampaignEntity', verbose_name='اردو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name_plural': 'رزرو اردو',
                'db_table': 'registered_users',
            },
            bases=(commons.models.base_entity.BaseEntity, models.Model),
        ),
    ]
