# Generated by Django 2.2 on 2020-10-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20201012_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignentity',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
