# Generated by Django 2.2 on 2020-10-13 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_auto_20201012_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignentity',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaignentity',
            name='deletion_time',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='campaignentity',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='campaignentity',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
