# Generated by Django 2.2 on 2020-10-13 22:32

import commons.models.base_entity
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserve', '0005_auto_20201013_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('deletion_time', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_users', to='reserve.CampaignEntity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(commons.models.base_entity.BaseEntity, models.Model),
        ),
    ]
