# Generated by Django 2.2 on 2020-11-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_registeredusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignentity',
            name='creator',
        ),
        migrations.AddField(
            model_name='campaignentity',
            name='Registration_time_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignentity',
            name='Registration_time_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignentity',
            name='execution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignentity',
            name='image',
            field=models.ImageField(default='Images/None/No_img.jpg', upload_to='Images/'),
        ),
        migrations.DeleteModel(
            name='RegisteredUsers',
        ),
    ]
