# Generated by Django 2.2 on 2020-12-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0009_remove_campaignentity_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignentity',
            name='capacity',
            field=models.IntegerField(default=20),
        ),
    ]
