# Generated by Django 2.2 on 2020-12-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_campaignentity_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignentity',
            name='year_of_entry',
            field=models.CharField(default=1395, max_length=50),
            preserve_default=False,
        ),
    ]
