# Generated by Django 2.2 on 2020-12-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0012_registeredusers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campaignentity',
            table='campaign_entity',
        ),
        migrations.AlterModelTable(
            name='registeredusers',
            table='registered_users',
        ),
    ]
