# Generated by Django 2.2 on 2020-12-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0014_auto_20201217_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='calceled_by',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'simple')], default=2),
        ),
    ]
