# Generated by Django 2.2 on 2020-12-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0015_registeredusers_calceled_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredusers',
            name='calceled_by',
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='canceled_by',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'simple')], default=None),
        ),
    ]
