# Generated by Django 2.2 on 2021-01-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0016_auto_20201218_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignentity',
            options={'verbose_name_plural': 'Camps'},
        ),
        migrations.AlterModelOptions(
            name='registeredusers',
            options={'verbose_name_plural': 'Registered users'},
        ),
    ]
