# Generated by Django 2.2 on 2021-01-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0017_auto_20210115_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignentity',
            name='Registration_time_1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع ثبت نام'),
        ),
        migrations.AlterField(
            model_name='campaignentity',
            name='Registration_time_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان ثبت نام'),
        ),
        migrations.AlterField(
            model_name='campaignentity',
            name='cancel_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ کنسلی اردو'),
        ),
        migrations.AlterField(
            model_name='campaignentity',
            name='capacity',
            field=models.IntegerField(default=20, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='campaignentity',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='هزینه'),
        ),
        migrations.AlterField(
            model_name='campaignentity',
            name='description',
            field=models.CharField(max_length=100, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='campaignentity',
            name='execution_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ برگزاری اردو'),
        ),
        migrations.AlterField(
            model_name='campaignentity',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='campaignentity',
            name='image',
            field=models.ImageField(default='Images/None/No_img.jpg', upload_to='Images/', verbose_name='بارگذاری پوستر اردو'),
        ),
        migrations.AlterField(
            model_name='campaignentity',
            name='is_canceled',
            field=models.BooleanField(default=0, verbose_name='کنسل شده است'),
        ),
        migrations.AlterField(
            model_name='campaignentity',
            name='is_verified',
            field=models.BooleanField(verbose_name='تایید شده است'),
        ),
        migrations.AlterField(
            model_name='campaignentity',
            name='name',
            field=models.CharField(max_length=30, verbose_name='عنوان اردو'),
        ),
        migrations.AlterField(
            model_name='campaignentity',
            name='verification_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید اردو'),
        ),
        migrations.AlterField(
            model_name='campaignentity',
            name='year_of_entry',
            field=models.CharField(max_length=50, verbose_name='سال ورودی'),
        ),
    ]
