# Generated by Django 2.2 on 2021-01-15 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0018_auto_20210115_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredusers',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_users', to='reserve.CampaignEntity', verbose_name='اردو'),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='cancel_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ کنسلی'),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='canceled_by',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'simple')], default=None, verbose_name='کنسل شده توسط'),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='is_canceled',
            field=models.BooleanField(default=0, verbose_name='کنسل شده است'),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو'),
        ),
    ]
