# Generated by Django 2.2 on 2021-01-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0019_auto_20210115_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredusers',
            name='cancel_time',
        ),
        migrations.RemoveField(
            model_name='registeredusers',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='registeredusers',
            name='deletion_time',
        ),
        migrations.RemoveField(
            model_name='registeredusers',
            name='last_update_time',
        ),
    ]
