# Generated by Django 2.2 on 2020-10-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignentity',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='campaignentity',
            name='year_of_entry',
        ),
    ]
