# Generated by Django 3.1.2 on 2020-11-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_registeredusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignentity',
            name='image',
            field=models.ImageField(default='Images/None/No_img.jpg', upload_to='Images/'),
        ),
    ]
