# Generated by Django 3.1.2 on 2020-11-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_campaignentity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignentity',
            name='Registration_time_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignentity',
            name='Registration_time_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignentity',
            name='execution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
