# Generated by Django 3.1.2 on 2020-11-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20201118_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignentity',
            name='creator',
        ),
    ]
