"""
Django settings for campaign_site project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from datetime import timedelta

from commons.config.runtime_config import RuntimeConfig

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '464b^-%p8jho-t=rykz0a!mtv03f2fyzv)r0l2%+y7kf0h!q75'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = RuntimeConfig.DEBUG

ALLOWED_HOSTS = RuntimeConfig.ALLOWED_HOSTS

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'identity.mobile_backend.ModelBackend',
]

# Email Setting
EMAIL_BACKEND = RuntimeConfig.EMAIL_BACKEND
EMAIL_HOST = RuntimeConfig.EMAIL_HOST
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = RuntimeConfig.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = RuntimeConfig.EMAIL_HOST_PASSWORD

#templated-email
DEFAULT_FROM_EMAIL = RuntimeConfig.EMAIL_HOST_USER
DOMAIN = RuntimeConfig.DOMAIN_NAME

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',

    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'djoser',

    'identity',
    'commons',
    'reserve',

    'corsheaders',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

DJOSER = {
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': '#/activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': True,
    'SET_PASSWORD_RETYPE': True,
    'SERIALIZERS': {},
}

AUTH_USER_MODEL = 'identity.UserEntity'

ROOT_URLCONF = 'campaign_site.urls'

SITE_NAME = 'Campaign Reserving'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'campaign_site.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': RuntimeConfig.MYSQL_DB_SCHEMA,
        'USER': RuntimeConfig.MYSQL_DB_USERNAME,
        'PASSWORD': RuntimeConfig.MYSQL_DB_PASSWORD,
        'HOST': RuntimeConfig.MYSQL_DB_URL,  # Or an IP Address that your DB is hosted on
        'PORT': RuntimeConfig.MYSQL_DB_PORT,
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
Kavenegar_API = '************'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': RuntimeConfig.AUTHENTICATION_CLASSES,
    'DEFAULT_PERMISSION_CLASSES': RuntimeConfig.REST_FRAMEWORK_DEFAULT_PERMISSION_CLASSES,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('JWT', 'Token',),
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
